sudo: required
language: python
services:
  - docker
before_install:
  - docker build -t roboticbase/ogc-poc1-device .
script:
  - docker run roboticbase/ogc-poc1-device /bin/bash -c "pip3 install -r requirements/develop.txt"
  - docker run roboticbase/ogc-poc1-device /bin/bash -c "python3 -m unittest discover tests"
